"""nmr — Numerai V2 quantitative research framework.

The `nmr` package is the single tested system boundary. Notebooks and scripts
are a thin control plane; all logic lives here and is covered by `tests/`.
"""

from __future__ import annotations

from .analysis import (
    FeatureCorrResult,
    SplitStats,
    benchmark_era_corr,
    cross_set_membership,
    describe_splits,
    era_structure,
    feature_correlation_structure,
    feature_drift_psi,
    feature_drift_profile,
    feature_ic_by_era,
    feature_ic_by_split,
    feature_ic_screen,
    feature_summary,
    meta_orthogonality,
    neutralized_ic_profile,
    neutralized_ic_series,
    regime_analysis,
    target_correlation_matrix,
    target_profile,
    within_set_redundancy,
)
from .benchmark import (
    NULL_BASELINES,
    TUTORIAL_NOTEBOOK_TO_MODEL_ID,
    BenchmarkSuite,
    assert_notebook_prediction_contract,
    assert_null_floor,
    assert_slice1_monotone,
    canonical_scorecards_bytes,
    discover_tutorial_notebooks,
    extract_oos_predictions,
    ingest_tutorial_prediction,
    ingest_tutorial_prediction_batch,
    scorecards_sha256,
    scorecards_to_frame,
    write_scorecards_csv,
)
from .campaign import (
    CampaignConfig,
    CampaignLog,
    CampaignRun,
    build_campaign_log,
    campaign_id,
    write_campaign_log,
)
from .config import (
    REPO_ROOT,
    DataConfig,
    EnsembleConfig,
    EvalConfig,
    ExperimentConfig,
    ModelConfig,
    RiskConfig,
    RunConfig,
    SplitConfig,
    load_config,
    set_global_seeds,
)
from .data import IngestionAgent
from .deployment import DeploymentArtifact, load_predict, serialize_predict
from .ensemble import Ensembler
from .evaluation import (
    MIN_OVERLAP_ERAS,
    EvaluationEngine,
    MetricSummary,
    NonVacuityError,
    clean_frame,
    downside_era_indices,
    per_era_turnover,
    sorted_era_labels,
)
from .features import (
    feature_stability_screen,
    resolve_feature_sets,
    resolve_small_feature_set,
    select_stable_features,
)
from .hardware import (
    GpuDevice,
    HardwareSpec,
    HardwareStatus,
    discover_hardware,
    gpu_devices,
    gpu_status,
    hardware_status,
    parse_cpu_times,
    parse_gpu_devices,
    parse_gpu_status,
    parse_meminfo,
)
from .inference import (
    BootstrapCI,
    SeriesStats,
    ac_adjusted_sharpe,
    benjamini_hochberg,
    block_bootstrap_ci,
    block_bootstrap_pvalue,
    deflated_sharpe,
    deflated_sharpe_fleet,
    era_series_stats,
    resolve_bandwidth,
    resolve_block_len,
)
from .meta import (
    CampaignEvidence,
    PairedResult,
    campaign_evidence,
    fleet_summary,
    paired_era_comparison,
    promotion_verdict,
)
from .models import CVResult, ModelOrchestrator, coerce_float32_features
from .opt import bayesian_sweep
from .payout import (
    OverlappingSimulationResult,
    PayoutResult,
    PayoutSeries,
    annual_compounded_return,
    burn_rate,
    calmar,
    cvar,
    gain_to_pain_ratio,
    kelly_fraction,
    max_burn_streak,
    max_drawdown,
    payout_report,
    payout_series,
    simulate_overlapping_portfolio,
    sortino,
    time_to_recovery,
)
from .registry import RunRegistry
from .refresh import (
    CURRENT_DATA_VERSION,
    EXPANDING_FILES,
    LIVE_FRESH_FILES,
    STATIC_FILES,
    build_era_manifest,
    classify_refresh_plan,
    detect_newer_version,
    needs_live_refresh,
)
from .research import (
    HyperparameterSweep,
    NeutralizationFrontier,
    SweepResult,
    feature_exposure_report,
    neutralization_frontier,
)
from .risk import NeutralizationEngine
from .robustness import (
    HorizonStabilityResult,
    PerturbationResult,
    RegimeCorr,
    adversarial_perturbation,
    regime_conditioned_corr,
    time_horizon_stability,
)
from .runner import ExperimentRunner, RunResult
from .scorecard import MetricCell, MetricScorecard, evaluate_model
from .splitter import Fold, PurgedEraSplitter
from .submission import build_submission, validate_submission, write_submission

__all__ = [
    "FeatureCorrResult",
    "SplitStats",
    "benchmark_era_corr",
    "cross_set_membership",
    "describe_splits",
    "era_structure",
    "feature_correlation_structure",
    "feature_drift_psi",
    "feature_drift_profile",
    "feature_ic_by_era",
    "feature_ic_by_split",
    "feature_ic_screen",
    "feature_summary",
    "meta_orthogonality",
    "neutralized_ic_profile",
    "neutralized_ic_series",
    "regime_analysis",
    "target_correlation_matrix",
    "target_profile",
    "within_set_redundancy",
    "REPO_ROOT",
    "DataConfig",
    "SplitConfig",
    "ModelConfig",
    "EvalConfig",
    "RiskConfig",
    "EnsembleConfig",
    "RunConfig",
    "ExperimentConfig",
    "load_config",
    "set_global_seeds",
    "NULL_BASELINES",
    "TUTORIAL_NOTEBOOK_TO_MODEL_ID",
    "BenchmarkSuite",
    "scorecards_to_frame",
    "write_scorecards_csv",
    "discover_tutorial_notebooks",
    "assert_notebook_prediction_contract",
    "extract_oos_predictions",
    "ingest_tutorial_prediction",
    "ingest_tutorial_prediction_batch",
    "assert_null_floor",
    "assert_slice1_monotone",
    "bayesian_sweep",
    "canonical_scorecards_bytes",
    "scorecards_sha256",
    "CampaignConfig",
    "CampaignRun",
    "CampaignLog",
    "build_campaign_log",
    "campaign_id",
    "write_campaign_log",
    "IngestionAgent",
    "DeploymentArtifact",
    "serialize_predict",
    "load_predict",
    "Ensembler",
    "CVResult",
    "coerce_float32_features",
    "CURRENT_DATA_VERSION",
    "EXPANDING_FILES",
    "ModelOrchestrator",
    "MetricSummary",
    "EvaluationEngine",
    "MIN_OVERLAP_ERAS",
    "NonVacuityError",
    "clean_frame",
    "downside_era_indices",
    "per_era_turnover",
    "sorted_era_labels",
    "feature_stability_screen",
    "resolve_feature_sets",
    "resolve_small_feature_set",
    "select_stable_features",
    "GpuDevice",
    "HardwareSpec",
    "HardwareStatus",
    "discover_hardware",
    "gpu_devices",
    "gpu_status",
    "hardware_status",
    "parse_cpu_times",
    "parse_gpu_devices",
    "parse_gpu_status",
    "parse_meminfo",
    "SeriesStats",
    "BootstrapCI",
    "era_series_stats",
    "resolve_block_len",
    "resolve_bandwidth",
    "block_bootstrap_ci",
    "block_bootstrap_pvalue",
    "benjamini_hochberg",
    "ac_adjusted_sharpe",
    "deflated_sharpe",
    "deflated_sharpe_fleet",
    "LIVE_FRESH_FILES",
    "STATIC_FILES",
    "build_era_manifest",
    "classify_refresh_plan",
    "detect_newer_version",
    "needs_live_refresh",
    "CampaignEvidence",
    "PairedResult",
    "campaign_evidence",
    "fleet_summary",
    "paired_era_comparison",
    "promotion_verdict",
    "OverlappingSimulationResult",
    "PayoutSeries",
    "PayoutResult",
    "annual_compounded_return",
    "payout_series",
    "payout_report",
    "burn_rate",
    "cvar",
    "gain_to_pain_ratio",
    "kelly_fraction",
    "sortino",
    "max_drawdown",
    "calmar",
    "max_burn_streak",
    "simulate_overlapping_portfolio",
    "time_to_recovery",
    "NeutralizationEngine",
    "PerturbationResult",
    "HorizonStabilityResult",
    "RegimeCorr",
    "adversarial_perturbation",
    "time_horizon_stability",
    "regime_conditioned_corr",
    "MetricCell",
    "MetricScorecard",
    "evaluate_model",
    "RunResult",
    "ExperimentRunner",
    "RunRegistry",
    "SweepResult",
    "HyperparameterSweep",
    "NeutralizationFrontier",
    "neutralization_frontier",
    "feature_exposure_report",
    "Fold",
    "PurgedEraSplitter",
    "build_submission",
    "validate_submission",
    "write_submission",
    "__version__",
]
__version__ = "0.1.0"
